<?php
    $lang2googlelan = array(
        "af" => "af", "am" => "am", "ar" => "ar", "az" => "az",
        "be" => "be", "bg_BG" => "bg", "bn_BD" => "bn", "bs_BA" => "bs",
        "ca" => "ca", "ceb" => "ceb", "co" => "co", "cs" => "cs",
        "cy" => "cy", "da_DK" => "da", "de_DE" => "de", "el" => "el",
        "en_US" => "en", "en_AU" => "en", "en_CA" => "en", "en_GB" => "en",
        "eo" => "eo", "es_ES" => "es", "es_AR" => "es", "es_CL" => "es",
        "es_CO" => "es", "es_MX" => "es", "es_PE" => "es", "es_PR" => "es",
        "es_VE" => "es", "et" => "et", "eu" => "eu", "fa_IR" => "fa",
        "fa_AF" => "fa", "fi" => "fi", "fr_BE" => "fr", "fr_FR" => "fr",
        "fy" => "fy", "ga" => "ga", "gd" => "gd", "gl_ES" => "gl",
        "gu_IN" => "gu", "haz" => "ha", "haw_US" => "haw", "he_IL" => "he",
        "hi_IN" => "hi", "hmn" => "hmn", "hr" => "hr", "ht" => "ht",
        "hu_HU" => "hu", "hy" => "hy", "id_ID" => "id", "ig" => "ig",
        "is_IS" => "is", "it_IT" => "it", "iw" => "iw", "ja" => "ja",
        "jw" => "jw", "ka_GE" => "ka", "kk" => "kk", "km" => "km",
        "kn" => "kn", "ko_KR" => "ko", "ku" => "ku", "ky_KY" => "ky",
        "la" => "la", "lb_LU" => "lb", "lo" => "lo", "lt_LT" => "lt",
        "lv" => "lv", "mg_MG" => "mg", "mi" => "mi", "mk_MK" => "mk",
        "ml_IN" => "ml", "mn" => "mn", "mr" => "mr", "ms_MY" => "ms",
        "mt" => "mt", "my_MM" => "my", "ne_NP" => "ne", "nl_NL" => "nl",
        "nl_BE" => "nl", "nn_NO" => "no", "ny" => "ny", "ory" => "or",
        "pa_IN" => "pa", "pl_PL" => "pl", "ps" => "ps", "pt_BR" => "pt",
        "pt_PT" => "pt", "ro_RO" => "ro", "ru_RU" => "ru", "rw" => "rw",
        "sd_PK" => "sd", "si_SK" => "si", "sk_SK" => "sk", "sl_SI" => "sl",
        "sm" => "sm", "sn" => "sn", "so_SO" => "so", "sq" => "sq",
        "sr_RS" => "sr", "st" => "st", "su_ID" => "su", "sv_SE" => "sv",
        "sw" => "sw", "ta_IN" => "ta", "te" => "te", "tg" => "tg",
        "th" => "th", "tk" => "tk", "tl" => "tl", "tr_TR" => "tr",
        "tt_RU" => "tt", "ug_CN" => "ug", "uk" => "uk", "ur" => "ur",
        "uz_UZ" => "uz", "vi" => "vi", "xh" => "xh", "yi" => "yi",
        "yor" => "yo", "zh" => "zh", "zh_CN" => "zh-CN", "zh_TW" => "zh-TW",
        "zu" => "zu", "zh-CN" => "zh-CN", "en-US" => "en",
        "bn-BD" => "bn", "bs-BA" => "bs", "da-DK" => "da", "de-DE" => "de",
        "en-US" => "en", "en-AU" => "en", "en-CA" => "en", "en-GB" => "en",
        "es-ES" => "es", "es-AR" => "es", "es-CL" => "es", "es-CO" => "es",
        "es-MX" => "es", "es-PE" => "es", "es-PR" => "es", "es-VE" => "es", 
        "fa-IR" => "fa", "fa-AF" => "fa", "fr-BE" => "fr", "fr-FR" => "fr",
        "gl-ES" => "gl", "gu-IN" => "gu", "haw-US" => "haw", "he-IL" => "he",
        "hi-IN" => "hi", "hu-HU" => "hu", "id-ID" => "id", "is-IS" => "is", 
        "it-IT" => "it", "ko-KR" => "ko", "ky-KY" => "ky", "lb-LU" => "lb", 
        "lt-LT" => "lt", "mk-MK" => "mk", "ml-IN" => "ml", "ms-MY" => "ms",
        "my-MM" => "my", "ne-NP" => "ne", "nl-NL" => "nl", "nl-BE" => "nl", 
        "nn-NO" => "no", "pa-IN" => "pa", "pl-PL" => "pl", "pt-BR" => "pt",
        "pt-PT" => "pt", "ro-RO" => "ro", "ru-RU" => "ru", "sd-PK" => "sd", 
        "sk-SK" => "sk", "sl-SI" => "sl", "su-ID" => "su", "sv-SE" => "sv",
        "tr-TR" => "tr", "tt-RU" => "tt", "zh-CN" => "zh-CN", 
        "zh-TW" => "zh-TW"
    );

?>
